@extends('include.admindashboard')

@section('body')
   <div class="page-content"><div class="container"><div class="row"><div class="main-content col-lg-12"><div class="content-area card"><div class="card-innr"><div class="card-head"><h4 class="card-title">Profile Details</h4></div><ul class="nav nav-tabs nav-tabs-line" role="tablist"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#personal-data">Personal Data</a></li> <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#password">Password</a></li></ul><!-- .nav-tabs-line --><div class="tab-content" id="profile-details"><div class="tab-pane fade show active" id="personal-data"><form class="form-horizontal" role="form" action="{{url('admin/profile')}}" method="post"
                          enctype="multipart/form-data">
                        @csrf
<input type="hidden" name="id" value="{{$admin->id}}">
                        <div class="row"><div class="col-md-6"><div class="input-item input-with-label"><label for="full-name" class="input-item-label">Full Name</label><input class="input-bordered" type="text" placeholder="Your Name" id="full-name" name="name" value="{{$admin->name}}"></div><!-- .input-item --></div><div class="col-md-6"><div class="input-item input-with-label"><label for="email-address" class="input-item-label">Email Address</label><input class="input-bordered" type="text" id="email-address" type="email" name="email" value="{{$admin->email}}"></div><!-- .input-item --></div><div class="col-md-6"><div class="input-item input-with-label"><label for="mobile-number" class="input-item-label">Mobile Number</label><input class="input-bordered" type="text" id="mobile-number" name="mobile" value="{{$admin->mobile}}" placeholder="Phone Number"></div><!-- .input-item --></div><div class="col-md-6"><div class="input-item input-with-label">

                        <div class="input-item input-with-label"><label for="nationality" class="input-item-label">Upload Avatar</label><div class="relative"><em class="input-file-icon fas fa-upload"></em><input type="file" class="input-file" id="file-01" name="image" accept="image/*"><label for="file-01">Choose a file</label></div></div>

                        </div> </div><!-- .col --></div><!-- .row --><div class="gaps-1x"></div><!-- 10px gap --><div class="d-sm-flex justify-content-between align-items-center"><button class="btn btn-primary" type="submit">Update Profile</button></form><div class="gaps-2x d-sm-none"></div> </div></form><!-- form --></div> <div class="tab-pane fade" id="password">

  <form class="form-horizontal" role="form" action="{{url('admin/change-password')}}" method="post">
  @csrf
<div class="row"><div class="col-md-6"><div class="input-item input-with-label">
    <label for="old-pass" class="input-item-label">Old Password</label><input class="input-bordered" type="password" id="old-pass" name="old_password"></div><!-- .input-item --></div><!-- .col --></div><!-- .row --><div class="row"><div class="col-md-6"><div class="input-item input-with-label"><label for="new-pass" class="input-item-label">New Password</label><input class="input-bordered" type="password" id="new-pass" name="new_password"></div><!-- .input-item --></div><!-- .col --><div class="col-md-6"><div class="input-item input-with-label"><label for="confirm-pass" class="input-item-label">Confirm New Password</label><input class="input-bordered" type="password" id="confirm-pass"  name="password_confirmation"></div><!-- .input-item --></div><!-- .col --></div><!-- .row --><div class="note note-plane note-info pdb-1x"><em class="fas fa-info-circle"></em><p>Password should be minmum 8 letter and include lower and uppercase letter.</p></div><div class="gaps-1x"></div><!-- 10px gap --><div class="d-sm-flex justify-content-between align-items-center"><button class="btn btn-primary">Update</button><div class="gaps-2x d-sm-none"></div> </div></div><!-- .tab-pane --></form></div><!-- .tab-content --></div><!-- .card-innr --></div><!-- .card --> </div><!-- .container --></div><!-- .container --></div><!-- .page-content -->@stop
